POST http://localhost:9090/api/v1/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzQXQiOjE3MjE1MzMxMjQsInVzZXJJRCI6IjEifQ.0VVEOW-mxh4EZn_9cq0KsesiAyZ7gcn6JZ-l3wNv3h4

{
    "name": "Dell Spire",
    "description": "Intel Core i7-1355U Gaming Laptop",
    "image": "Dell-i7-1335u-laptop.png",
    "price": 4000,
    "quantity": 1000
}